// This file is @generated by prost-build.
/// Игрок
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GamePlayer {
    /// Имя игрока (для отображения в интерфейсе)
    #[prost(string, required, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Уникальный идентификатор игрока в пределах игры
    #[prost(int32, required, tag = "2")]
    pub id: i32,
    /// IPv4 или IPv6 адрес игрока в виде строки. Отсутствует в описании игрока-отправителя сообщения
    #[prost(string, optional, tag = "3")]
    pub ip_address: ::core::option::Option<::prost::alloc::string::String>,
    /// Порт UDP-сокета игрока. Отсутствует в описании игрока-отправителя сообщения
    #[prost(int32, optional, tag = "4")]
    pub port: ::core::option::Option<i32>,
    /// Роль узла в топологии
    #[prost(enumeration = "NodeRole", required, tag = "5")]
    pub role: i32,
    /// Тип игрока
    #[prost(enumeration = "PlayerType", optional, tag = "6", default = "Human")]
    pub r#type: ::core::option::Option<i32>,
    /// Число очков, которые набрал игрок
    #[prost(int32, required, tag = "7")]
    pub score: i32,
}
/// Параметры идущей игры (не должны меняться в процессе игры)
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GameConfig {
    /// Ширина поля в клетках (от 10 до 100)
    #[prost(int32, optional, tag = "1", default = "40")]
    pub width: ::core::option::Option<i32>,
    /// Высота поля в клетках (от 10 до 100)
    #[prost(int32, optional, tag = "2", default = "30")]
    pub height: ::core::option::Option<i32>,
    /// Количество клеток с едой, независимо от числа игроков (от 0 до 100)
    #[prost(int32, optional, tag = "3", default = "1")]
    pub food_static: ::core::option::Option<i32>,
    /// Задержка между ходами (сменой состояний) в игре, в миллисекундах (от 100 до 3000)
    #[prost(int32, optional, tag = "5", default = "1000")]
    pub state_delay_ms: ::core::option::Option<i32>,
}
/// Игроки конкретной игры
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GamePlayers {
    /// Список всех игроков
    #[prost(message, repeated, tag = "1")]
    pub players: ::prost::alloc::vec::Vec<GamePlayer>,
}
/// Текущее состояние игрового поля
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameState {
    /// Порядковый номер состояния, уникален в пределах игры, монотонно возрастает
    #[prost(int32, required, tag = "1")]
    pub state_order: i32,
    /// Список змей
    #[prost(message, repeated, tag = "2")]
    pub snakes: ::prost::alloc::vec::Vec<game_state::Snake>,
    /// Список клеток с едой
    #[prost(message, repeated, tag = "3")]
    pub foods: ::prost::alloc::vec::Vec<game_state::Coord>,
    /// Актуальнейший список игроков
    #[prost(message, required, tag = "4")]
    pub players: GamePlayers,
}
/// Nested message and enum types in `GameState`.
pub mod game_state {
    /// Координаты в пределах игрового поля, либо относительное смещение координат.
    /// Левая верхняя клетка поля имеет координаты (x=0, y=0).
    /// Направление смещения задаётся знаком чисел.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Coord {
        /// По горизонтальной оси, положительное направление - вправо
        #[prost(sint32, optional, tag = "1", default = "0")]
        pub x: ::core::option::Option<i32>,
        /// По вертикальной оси, положительное направление - вниз
        #[prost(sint32, optional, tag = "2", default = "0")]
        pub y: ::core::option::Option<i32>,
    }
    /// Змея
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Snake {
        /// Идентификатор игрока-владельца змеи, см. GamePlayer.id
        #[prost(int32, required, tag = "1")]
        pub player_id: i32,
        /// Список "ключевых" точек змеи. Первая точка хранит координаты головы змеи.
        /// Каждая следующая - смещение следующей "ключевой" точки относительно предыдущей,
        /// в частности последняя точка хранит смещение хвоста змеи относительно предыдущей "ключевой" точки.
        #[prost(message, repeated, tag = "2")]
        pub points: ::prost::alloc::vec::Vec<Coord>,
        /// статус змеи в игре
        #[prost(
            enumeration = "snake::SnakeState",
            required,
            tag = "3",
            default = "Alive"
        )]
        pub state: i32,
        /// Направление, в котором "повёрнута" голова змейки в текущий момент
        #[prost(enumeration = "super::Direction", required, tag = "4")]
        pub head_direction: i32,
    }
    /// Nested message and enum types in `Snake`.
    pub mod snake {
        /// Статус змеи в игре
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum SnakeState {
            /// Змея управляется игроком
            Alive = 0,
            /// Змея принадлежала игроку, который вышел из игры, она продолжает движение куда глаза глядят
            Zombie = 1,
        }
        impl SnakeState {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Alive => "ALIVE",
                    Self::Zombie => "ZOMBIE",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "ALIVE" => Some(Self::Alive),
                    "ZOMBIE" => Some(Self::Zombie),
                    _ => None,
                }
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameAnnouncement {
    /// Текущие игроки
    #[prost(message, required, tag = "1")]
    pub players: GamePlayers,
    /// Параметры игры
    #[prost(message, required, tag = "2")]
    pub config: GameConfig,
    /// Можно ли новому игроку присоединиться к игре (есть ли место на поле)
    #[prost(bool, optional, tag = "3", default = "true")]
    pub can_join: ::core::option::Option<bool>,
    /// Глобально уникальное имя игры, например "my game"
    #[prost(string, required, tag = "4")]
    pub game_name: ::prost::alloc::string::String,
}
/// Общий формат любого UDP-сообщения
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameMessage {
    /// Порядковый номер сообщения, уникален для отправителя в пределах игры, монотонно возрастает
    #[prost(int64, required, tag = "1")]
    pub msg_seq: i64,
    /// ID игрока-отправителя этого сообщения (обязательно для AckMsg и RoleChangeMsg)
    #[prost(int32, optional, tag = "10")]
    pub sender_id: ::core::option::Option<i32>,
    /// ID игрока-получателя этого сообщения (обязательно для AckMsg и RoleChangeMsg)
    #[prost(int32, optional, tag = "11")]
    pub receiver_id: ::core::option::Option<i32>,
    /// Тип сообщения
    #[prost(oneof = "game_message::Type", tags = "2, 3, 4, 5, 6, 7, 8, 9, 12")]
    pub r#type: ::core::option::Option<game_message::Type>,
}
/// Nested message and enum types in `GameMessage`.
pub mod game_message {
    /// Ничего не меняем, просто говорим, что мы живы
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct PingMsg {}
    /// Не-центральный игрок просит повернуть голову змеи
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct SteerMsg {
        /// Куда повернуть на следующем шаге
        #[prost(enumeration = "super::Direction", required, tag = "1")]
        pub direction: i32,
    }
    /// Подтверждение сообщения с таким же seq
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct AckMsg {}
    /// Центральный узел сообщает остальным игрокам состояние игры
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct StateMsg {
        /// Состояние игрового поля
        #[prost(message, required, tag = "1")]
        pub state: super::GameState,
    }
    /// Уведомление об идущих играх, регулярно отправляется multicast-ом или в ответ на DiscoverMsg
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct AnnouncementMsg {
        /// Идущие игры (в текущей версии задачи тут всегда ровно одна игра)
        #[prost(message, repeated, tag = "1")]
        pub games: ::prost::alloc::vec::Vec<super::GameAnnouncement>,
    }
    /// Запрос информации об идущих играх
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct DiscoverMsg {}
    /// Новый игрок хочет присоединиться к идущей игре
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct JoinMsg {
        /// Тип присоединяющегося игрока
        #[prost(
            enumeration = "super::PlayerType",
            optional,
            tag = "1",
            default = "Human"
        )]
        pub player_type: ::core::option::Option<i32>,
        /// Имя игрока
        #[prost(string, required, tag = "3")]
        pub player_name: ::prost::alloc::string::String,
        /// Глобально уникальное имя игры, к которой хотим присоединиться
        #[prost(string, required, tag = "4")]
        pub game_name: ::prost::alloc::string::String,
        /// NORMAL, если хотим играть; VIEWER, если хотим только понаблюдать; остальные значения недопустимы
        #[prost(enumeration = "super::NodeRole", required, tag = "5")]
        pub requested_role: i32,
    }
    /// Ошибка операции (например отказ в присоединении к игре, т.к. нет места на поле)
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ErrorMsg {
        /// Строковое сообщение, нужно отобразить его на экране, не блокируя работу программы
        #[prost(string, required, tag = "1")]
        pub error_message: ::prost::alloc::string::String,
    }
    /// Сообщение о смене роли:
    /// 1. от заместителя другим игрокам о том, что пора начинать считать его главным (sender_role = MASTER)
    /// 2. от осознанно выходящего игрока (sender_role = VIEWER)
    /// 3. от главного к умершему игроку (receiver_role = VIEWER)
    /// 4. в комбинации с 1,2 или отдельно от них: назначение кого-то заместителем (receiver_role = DEPUTY)
    /// 5. в комбинации с 2 от главного узла заместителю о том, что он становится главным (receiver_role = MASTER)
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct RoleChangeMsg {
        #[prost(enumeration = "super::NodeRole", optional, tag = "1")]
        pub sender_role: ::core::option::Option<i32>,
        #[prost(enumeration = "super::NodeRole", optional, tag = "2")]
        pub receiver_role: ::core::option::Option<i32>,
    }
    /// Тип сообщения
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag = "2")]
        Ping(PingMsg),
        #[prost(message, tag = "3")]
        Steer(SteerMsg),
        #[prost(message, tag = "4")]
        Ack(AckMsg),
        #[prost(message, tag = "5")]
        State(StateMsg),
        #[prost(message, tag = "6")]
        Announcement(AnnouncementMsg),
        #[prost(message, tag = "7")]
        Join(JoinMsg),
        #[prost(message, tag = "8")]
        Error(ErrorMsg),
        #[prost(message, tag = "9")]
        RoleChange(RoleChangeMsg),
        #[prost(message, tag = "12")]
        Discover(DiscoverMsg),
    }
}
/// Роль узла в топологии связей узлов в пределах игры
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeRole {
    /// Обычный узел, лист в топологии "звезда"
    Normal = 0,
    /// Главный узел, центр в топологии "звезда"
    Master = 1,
    /// Заместитель главного узла
    Deputy = 2,
    /// Наблюдатель, похож на NORMAL, но не имеет змеи в статусе ALIVE, только получает обновления статуса
    Viewer = 3,
}
impl NodeRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Normal => "NORMAL",
            Self::Master => "MASTER",
            Self::Deputy => "DEPUTY",
            Self::Viewer => "VIEWER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NORMAL" => Some(Self::Normal),
            "MASTER" => Some(Self::Master),
            "DEPUTY" => Some(Self::Deputy),
            "VIEWER" => Some(Self::Viewer),
            _ => None,
        }
    }
}
/// Тип игрока
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PlayerType {
    /// Живой пользователь
    Human = 0,
    /// Робот, управляет своей змеёй с помощью алгоритма (это не нужно реализовывать, но предусмотрено в протоколе на будущее)
    Robot = 1,
}
impl PlayerType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Human => "HUMAN",
            Self::Robot => "ROBOT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HUMAN" => Some(Self::Human),
            "ROBOT" => Some(Self::Robot),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Direction {
    /// Вверх (в отрицательном направлении оси y)
    Up = 1,
    /// Вниз (в положительном направлении оси y)
    Down = 2,
    /// Влево (в отрицательном направлении оси x)
    Left = 3,
    /// Вправо (в положительном направлении оси x)
    Right = 4,
}
impl Direction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Up => "UP",
            Self::Down => "DOWN",
            Self::Left => "LEFT",
            Self::Right => "RIGHT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UP" => Some(Self::Up),
            "DOWN" => Some(Self::Down),
            "LEFT" => Some(Self::Left),
            "RIGHT" => Some(Self::Right),
            _ => None,
        }
    }
}
